# -*- coding: utf-8 -*-
"""tugas-df-upload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQd9mYImrvhf32ukJxF1-UonzsZvX6cc
"""

try:
  import io
  from io import BytesIO
  import pandas as pd
  from google.cloud import storage

except Exception as e:
  print("Some Module Are Missing{}".format(e))

storage_client = storage.Client.from_service_account_json("/content/tugas-data-fellowship-8-2a9fbf79ab84.json")

# create a bucket object
bucket = storage_client.get_bucket("data-fellowship-8-bucket")

filename = "%s/%s" %('',"/content/221018 graduaation.jpg")
blob = bucket.blob(filename)

with open('/content/220818 Background zoom DF.jpg', 'rb') as f:
  blob.upload_from_file(f)

print("Upload completed")